name: ci-sonar-cloud
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run project tests
        run: npm test

      - name: Upload Code Coverage
        id: report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
