name: ci-sonar-cloud
on:
  pull_request:
    branches:
      - develop

jobs: 
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4 
        with:
          node-version: 18
      - run: npm install
      - run: npm test

      
