name: ci-sonar-cloud
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Upload Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov.info
